module.exports = [
  {
    id: 1,
    icon: 'laptop',
    name: 'Dashboard',
    router: '/dashboard',
  },
  {
    id: 21,
    mpid: -1,
    bpid: 2,
    name: 'User Detail',
    router: '/user/:id',
  },
  {
    id: 3,
    bpid: 1,
    icon: 'home',
    name: 'Company',
    router: '/company',
  },
  {
    id: 21,
    mpid: -1,
    bpid: 3,
    name: 'Company Detail',
    router: '/company/:id',
  },
  {
    id: 4,
    bpid: 1,
    icon: 'book',
    name: 'Contact Person',
    router: '/contact-person',
  },
  {
    id: 5,
    bpid: 1,
    icon: 'appstore-o',
    name: 'Equipment',
    router: '/equipment',
  },
  {
    id: 29,
    mpid: -1,
    bpid: 1,
    name: 'Equipment Detail',
    router: '/company/:id',
  },
  {
    id: 6,
    bpid: 1,
    icon: 'user-add',
    name: 'References',
    router: '/reference',
  },
  {
    id: 7,
    bpid: 1,
    name: 'Users Management',
    icon: 'user',
    router: '/user',
  },
]
